# Generated by Django 4.1.7 on 2023-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_alter_entry_options_topic_owner_alter_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='choice',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
