# Generated by Django 4.1.7 on 2023-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_alter_topic_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='choice',
            field=models.CharField(choices=[('PUB', 'public'), ('PRIV', 'private')], default='PUB', max_length=8),
        ),
    ]
