# Generated by Django 4.1.7 on 2023-03-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_alter_topic_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='choice',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=8),
        ),
    ]
